spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payment/**
server:
  port: 8080