server:
  port: 8091
spring:
  rabbitmq:
    host: localhost
  application:
    name: payment-service
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/localdevdb
    username: localdevuser
    password: pirate
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: localdevdb