version: '3.1'
services:
  payment-db:
    container_name: 'Payment-Container'
    image: postgres:alpine
    ports:
      - '5431:5432'
    environment:
      - POSTGRES_DB=localdevdb
      - POSTGRES_USER=localdevuser
      - POSTGRES_PASSWORD=pirate